/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Perpustakaan } from "./Perpustakaan";
export * as factories from "./factories";
export { Perpustakaan__factory } from "./factories/Perpustakaan__factory";
